Minimal changes to get Docker running
gdbelvin/keytransparency pull request #2
Opened 2017-06-07 13:38 UTC by Liamsi

Most relevant changes:
- fix `docker-compose up -d trillian-map` in Readme
- rename some vars in `cmd/keytransparency-server/Dockerfile`
- point to correct trillian keys 
- fix/mount directories (under `trillian/testfiles` while kt uses `genfiles`)
- fix flag for PEM file in [cmd/keytransparency-signer/backend.go](https://github.com/gdbelvin/keytransparency/compare/docker...Liamsi:docker?expand=1#diff-4e5c1435ea19ee06756ee522d62b883f); also provide the test-password on the command-line
- remove .env file and provide defaults in docker-compose.yml instead
- provide a default IP for the generated cert such that the IP SANs extension will be available

2017-06-07 20:05 UTC, gdbelvin commented on README.md
> +MAP_IP=`docker inspect keytransparency_trillian-map_1 | grep -E '"IPAddress": ' | tail -n 1 | cut -d \" -f 4`
MAP_IP should be injected into each HOSTS file by the docker cluster manager. This should not be needed. / Let's figure out how to avoid this.

2017-06-07 20:25 UTC, gdbelvin commented on README.md
> +MAP_IP=`docker inspect keytransparency_trillian-map_1 | grep -E '"IPAddress": ' | tail -n 1 | cut -d \" -f 4`
Looks like the format command is a bit more canonical way to do this:
`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id`

https://stackoverflow.com/questions/17157721/how-to-get-a-docker-containers-ip-address-from-the-host

2017-06-07 20:26 UTC, gdbelvin commented on cmd/keytransparency-server/Dockerfile
> +	--vrf="$VRF_PRIV" \
Is this change a mistake? I don't see a corresponding VRF_PRIV ENV variable above

2017-06-07 20:28 UTC, gdbelvin commented on cmd/keytransparency-signer/backend.go
> +	signer, err := keys.NewFromPrivatePEM(string(pemB), *signingKeyPassword)
There's a convenience method for this: `NewFromPrivatePEMPath`

2017-06-07 20:30 UTC, gdbelvin requested changes
Thanks for this PR! 

A couple changes are needed to clean things up and I'll merge it.

2017-06-08 09:57 UTC, Liamsi commented on cmd/keytransparency-signer/backend.go
> +	signer, err := keys.NewFromPrivatePEM(string(pemB), *signingKeyPassword)
Thanks! I changed it to `NewFromPrivatePEMFile`. Just a note: Now, there is a minor difference in behavior though: with [`NewFromPrivatePEM`](https://github.com/google/trillian/blob/0ddedc05cdabd5539a0d4c869db06c9ca5a29044/crypto/keys/private_keys.go#L74-L90) one could provide an empty password which isn't possible with [`NewFromPrivatePEMFile`](https://github.com/google/trillian/blob/0ddedc05cdabd5539a0d4c869db06c9ca5a29044/crypto/keys/private_keys.go#L57) anymore (and I think that makes more sense, too).

2017-06-08 10:06 UTC, Liamsi commented on cmd/keytransparency-server/Dockerfile
> +	--vrf="$VRF_PRIV" \
Good catch! I wanted consistent naming with `prepare_server.sh` where this variable is also called `VRF_PRIV`. I missed that I didn't rename the [default](https://github.com/gdbelvin/keytransparency/pull/2/files#diff-0e69bceb3e39e5774b7edcdc1aae92caL12) in this particular Dockerfile, though.

2017-06-09 10:37 UTC, gdbelvin approved these changes

2017-06-09 10:37 UTC, merged